In [1]:
import numpy as np
import pandas as pd

#### question 1

In [2]:
np.__version__

'1.21.1'

#### question 2

In [3]:
pd.__version__

'1.3.1'

In [8]:
# read data
df_cars = pd.read_csv('cars.csv', sep = ',', index_col = False)
df_cars.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [9]:
df_cars.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

#### question 3

In [10]:
# average price BMW
df_cars[df_cars.Make == 'BMW']['MSRP'].mean()

61546.76347305389

#### question 4

In [17]:
# Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). 
# How many of them have missing values for Engine HP?

len(df_cars[(df_cars.Year > 2014) & (df_cars['Engine HP'].isnull())])

51

#### question 5

In [18]:
# mean Engine HP
df_cars['Engine HP'].mean()

249.38607007176023

In [24]:
df_cars['Engine HP'] = df_cars['Engine HP'].fillna(249.386)

# check that there is no null value
df_cars[df_cars['Engine HP'].isnull() == True]

Empty DataFrame
Columns: [Make, Model, Year, Engine Fuel Type, Engine HP, Engine Cylinders, Transmission Type, Driven_Wheels, Number of Doors, Market Category, Vehicle Size, Vehicle Style, highway MPG, city mpg, Popularity, MSRP]
Index: []

In [20]:
# mean2 Engine HP
df_cars['Engine HP'].mean()

249.38606966593923

#### question 6

In [30]:
df_cars_rolls_royce = df_cars[df_cars.Make == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].reset_index(drop=True)
df_cars_rolls_royce = df_cars_rolls_royce.drop_duplicates()

In [42]:
df_cars_rolls_royce_array = df_cars_rolls_royce.to_numpy()
df_cars_rolls_royce_array

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [58]:
XTX = df_cars_rolls_royce_array.T.dot(df_cars_rolls_royce_array)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [59]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [60]:
np.sum(XTX_inv)

0.032212320677486125

#### question 7

In [63]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
w = XTX_inv.dot(df_cars_rolls_royce_array.T).dot(y)
w[0]

0.19989598183188978